// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cordic_cordic,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.280750,HLS_SYN_LAT=13,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1030,HLS_SYN_LUT=3727,HLS_VERSION=2020_2}" *)

module cordic (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [27:0] theta;
wire   [27:0] sine;
reg    sine_ap_vld;
wire   [27:0] cosine;
reg    cosine_ap_vld;
wire   [0:0] tmp_fu_222_p3;
reg   [0:0] tmp_reg_1596;
wire   [27:0] theta_V_fu_238_p2;
reg   [27:0] theta_V_reg_1604;
reg   [0:0] tmp_1_reg_1609;
reg   [0:0] tmp_2_reg_1615;
wire   [27:0] theta_V_1_fu_272_p2;
reg   [27:0] theta_V_1_reg_1620;
wire    ap_CS_fsm_state2;
reg   [0:0] tmp_3_reg_1625;
reg   [0:0] tmp_4_reg_1631;
wire   [27:0] theta_V_2_fu_306_p2;
reg   [27:0] theta_V_2_reg_1636;
wire    ap_CS_fsm_state3;
reg   [0:0] tmp_6_reg_1641;
reg   [0:0] tmp_7_reg_1647;
wire   [27:0] theta_V_3_fu_340_p2;
reg   [27:0] theta_V_3_reg_1652;
wire    ap_CS_fsm_state4;
reg   [0:0] tmp_9_reg_1657;
reg   [0:0] tmp_10_reg_1663;
wire   [27:0] theta_V_4_fu_374_p2;
reg   [27:0] theta_V_4_reg_1668;
wire    ap_CS_fsm_state5;
reg   [0:0] tmp_12_reg_1673;
reg   [0:0] tmp_13_reg_1679;
wire   [27:0] theta_V_5_fu_408_p2;
reg   [27:0] theta_V_5_reg_1684;
wire    ap_CS_fsm_state6;
reg   [0:0] tmp_15_reg_1689;
reg   [0:0] tmp_16_reg_1695;
wire   [27:0] theta_V_6_fu_442_p2;
reg   [27:0] theta_V_6_reg_1700;
wire    ap_CS_fsm_state7;
reg   [0:0] tmp_18_reg_1705;
reg   [0:0] tmp_19_reg_1711;
wire  signed [21:0] select_ln1496_5_fu_640_p3;
reg  signed [21:0] select_ln1496_5_reg_1716;
wire    ap_CS_fsm_state8;
wire   [25:0] current_sin_V_8_fu_647_p3;
reg   [25:0] current_sin_V_8_reg_1721;
reg   [17:0] tmp_8_reg_1727;
reg   [21:0] trunc_ln1333_4_reg_1732;
wire   [27:0] theta_V_7_fu_686_p2;
reg   [27:0] theta_V_7_reg_1737;
reg   [0:0] tmp_22_reg_1742;
reg   [0:0] tmp_23_reg_1748;
wire   [23:0] select_ln1496_11_fu_809_p3;
reg   [23:0] select_ln1496_11_reg_1753;
wire    ap_CS_fsm_state9;
wire   [25:0] current_sin_V_14_fu_816_p3;
reg   [25:0] current_sin_V_14_reg_1759;
reg   [17:0] tmp_14_reg_1765;
reg   [19:0] trunc_ln1333_8_reg_1770;
wire   [27:0] theta_V_8_fu_855_p2;
reg   [27:0] theta_V_8_reg_1775;
reg   [0:0] tmp_26_reg_1780;
reg   [0:0] tmp_27_reg_1786;
wire   [23:0] select_ln1496_17_fu_969_p3;
reg   [23:0] select_ln1496_17_reg_1791;
wire    ap_CS_fsm_state10;
wire   [25:0] current_sin_V_20_fu_976_p3;
reg   [25:0] current_sin_V_20_reg_1797;
reg   [15:0] tmp_20_reg_1803;
reg   [17:0] tmp_21_reg_1808;
wire   [27:0] theta_V_9_fu_1015_p2;
reg   [27:0] theta_V_9_reg_1813;
reg   [0:0] tmp_30_reg_1818;
reg   [0:0] tmp_31_reg_1824;
wire   [23:0] select_ln1496_23_fu_1129_p3;
reg   [23:0] select_ln1496_23_reg_1829;
wire    ap_CS_fsm_state11;
wire   [25:0] current_sin_V_26_fu_1136_p3;
reg   [25:0] current_sin_V_26_reg_1835;
reg   [13:0] tmp_28_reg_1841;
reg   [15:0] tmp_29_reg_1846;
wire   [27:0] theta_V_10_fu_1175_p2;
reg   [27:0] theta_V_10_reg_1851;
reg   [0:0] tmp_34_reg_1856;
reg   [0:0] tmp_35_reg_1862;
wire   [23:0] select_ln1496_29_fu_1289_p3;
reg   [23:0] select_ln1496_29_reg_1867;
wire    ap_CS_fsm_state12;
wire   [27:0] theta_V_11_fu_1308_p2;
reg   [27:0] theta_V_11_reg_1873;
wire   [25:0] current_sin_V_32_fu_1314_p3;
reg   [25:0] current_sin_V_32_reg_1878;
reg   [11:0] tmp_36_reg_1884;
reg   [13:0] tmp_37_reg_1889;
reg   [0:0] tmp_38_reg_1894;
reg   [0:0] tmp_39_reg_1900;
wire   [27:0] theta_V_12_fu_1402_p2;
reg   [27:0] theta_V_12_reg_1905;
wire    ap_CS_fsm_state13;
wire   [25:0] current_sin_V_35_fu_1408_p3;
reg   [25:0] current_sin_V_35_reg_1910;
reg   [10:0] tmp_40_reg_1916;
wire   [0:0] tmp_42_fu_1439_p3;
reg   [0:0] tmp_42_reg_1921;
wire   [23:0] select_ln1496_35_fu_1459_p3;
reg   [23:0] select_ln1496_35_reg_1926;
reg   [0:0] tmp_43_reg_1932;
reg   [9:0] tmp_44_reg_1937;
wire    ap_CS_fsm_state14;
wire   [27:0] select_ln31_1_fu_230_p3;
wire   [27:0] add_ln1496_fu_267_p2;
wire   [27:0] select_ln1496_fu_260_p3;
wire   [27:0] add_ln1496_2_fu_301_p2;
wire   [27:0] select_ln1496_3_fu_294_p3;
wire   [27:0] add_ln1496_4_fu_335_p2;
wire   [27:0] select_ln1496_6_fu_328_p3;
wire   [27:0] add_ln1496_6_fu_369_p2;
wire   [27:0] select_ln1496_9_fu_362_p3;
wire   [27:0] add_ln1496_8_fu_403_p2;
wire   [27:0] select_ln1496_12_fu_396_p3;
wire   [27:0] add_ln1496_10_fu_437_p2;
wire   [27:0] select_ln1496_15_fu_430_p3;
wire   [19:0] select_ln703_1_fu_478_p3;
wire   [19:0] select_ln703_fu_464_p3;
wire   [19:0] select_ln1333_fu_492_p3;
wire   [20:0] current_sin_V_1_fu_485_p3;
wire   [20:0] current_sin_V_fu_471_p3;
wire  signed [20:0] current_sin_V_2_fu_503_p3;
wire   [17:0] r_V_fu_514_p4;
wire   [18:0] trunc_ln2_fu_528_p4;
wire   [20:0] zext_ln1496_fu_499_p1;
wire  signed [20:0] sext_ln1496_fu_538_p1;
wire  signed [21:0] sext_ln20_fu_510_p1;
wire   [21:0] zext_ln1332_fu_524_p1;
wire   [20:0] add_ln703_fu_554_p2;
wire   [20:0] sub_ln703_fu_542_p2;
wire   [20:0] select_ln1496_2_fu_566_p3;
wire   [21:0] current_sin_V_4_fu_560_p2;
wire   [21:0] current_sin_V_3_fu_548_p2;
wire  signed [21:0] current_sin_V_5_fu_577_p3;
wire   [17:0] tmp_5_fu_588_p4;
wire   [18:0] trunc_ln1333_2_fu_602_p4;
wire   [21:0] zext_ln1496_1_fu_573_p1;
wire  signed [21:0] sext_ln1496_1_fu_612_p1;
wire  signed [25:0] sext_ln20_1_fu_584_p1;
wire   [25:0] zext_ln1332_1_fu_598_p1;
wire   [21:0] add_ln703_3_fu_628_p2;
wire   [21:0] sub_ln703_2_fu_616_p2;
wire   [25:0] current_sin_V_7_fu_634_p2;
wire   [25:0] current_sin_V_6_fu_622_p2;
wire   [27:0] add_ln1496_12_fu_681_p2;
wire   [27:0] select_ln1496_18_fu_674_p3;
wire  signed [22:0] sext_ln1496_2_fu_708_p1;
wire  signed [22:0] sext_ln1496_3_fu_714_p1;
wire  signed [25:0] sext_ln1332_fu_711_p1;
wire   [22:0] add_ln703_5_fu_728_p2;
wire   [22:0] sub_ln703_4_fu_717_p2;
wire  signed [22:0] select_ln1496_8_fu_739_p3;
wire   [25:0] current_sin_V_10_fu_734_p2;
wire   [25:0] current_sin_V_9_fu_723_p2;
wire   [17:0] tmp_11_fu_757_p4;
wire   [25:0] current_sin_V_11_fu_750_p3;
wire   [20:0] trunc_ln1333_6_fu_771_p4;
wire  signed [23:0] sext_ln1496_4_fu_746_p1;
wire  signed [23:0] sext_ln1496_5_fu_781_p1;
wire  signed [25:0] sext_ln1332_1_fu_767_p1;
wire   [23:0] add_ln703_7_fu_797_p2;
wire   [23:0] sub_ln703_6_fu_785_p2;
wire   [25:0] current_sin_V_13_fu_803_p2;
wire   [25:0] current_sin_V_12_fu_791_p2;
wire   [27:0] add_ln1496_14_fu_850_p2;
wire   [27:0] select_ln1496_21_fu_843_p3;
wire  signed [23:0] sext_ln1496_6_fu_880_p1;
wire  signed [25:0] sext_ln1332_2_fu_877_p1;
wire   [23:0] add_ln703_9_fu_893_p2;
wire   [23:0] sub_ln703_8_fu_883_p2;
wire   [25:0] current_sin_V_16_fu_898_p2;
wire   [25:0] current_sin_V_15_fu_888_p2;
wire   [23:0] select_ln1496_14_fu_903_p3;
wire   [16:0] tmp_17_fu_917_p4;
wire   [25:0] current_sin_V_17_fu_910_p3;
wire   [18:0] trunc_ln1333_s_fu_931_p4;
wire  signed [23:0] sext_ln1496_7_fu_941_p1;
wire  signed [25:0] sext_ln1333_fu_927_p1;
wire   [23:0] add_ln703_11_fu_957_p2;
wire   [23:0] sub_ln703_10_fu_945_p2;
wire   [25:0] current_sin_V_19_fu_963_p2;
wire   [25:0] current_sin_V_18_fu_951_p2;
wire   [27:0] add_ln1496_16_fu_1010_p2;
wire   [27:0] select_ln1496_24_fu_1003_p3;
wire  signed [23:0] sext_ln1496_8_fu_1040_p1;
wire  signed [25:0] sext_ln1333_1_fu_1037_p1;
wire   [23:0] add_ln703_13_fu_1053_p2;
wire   [23:0] sub_ln703_12_fu_1043_p2;
wire   [25:0] current_sin_V_22_fu_1058_p2;
wire   [25:0] current_sin_V_21_fu_1048_p2;
wire   [23:0] select_ln1496_20_fu_1063_p3;
wire   [14:0] tmp_24_fu_1077_p4;
wire   [25:0] current_sin_V_23_fu_1070_p3;
wire   [16:0] tmp_25_fu_1091_p4;
wire  signed [23:0] sext_ln1496_9_fu_1101_p1;
wire  signed [25:0] sext_ln1332_3_fu_1087_p1;
wire   [23:0] add_ln703_15_fu_1117_p2;
wire   [23:0] sub_ln703_14_fu_1105_p2;
wire   [25:0] current_sin_V_25_fu_1123_p2;
wire   [25:0] current_sin_V_24_fu_1111_p2;
wire   [27:0] add_ln1496_18_fu_1170_p2;
wire   [27:0] select_ln1496_27_fu_1163_p3;
wire  signed [23:0] sext_ln1496_10_fu_1200_p1;
wire  signed [25:0] sext_ln1332_4_fu_1197_p1;
wire   [23:0] add_ln703_17_fu_1213_p2;
wire   [23:0] sub_ln703_16_fu_1203_p2;
wire   [25:0] current_sin_V_28_fu_1218_p2;
wire   [25:0] current_sin_V_27_fu_1208_p2;
wire   [23:0] select_ln1496_26_fu_1223_p3;
wire   [12:0] tmp_32_fu_1237_p4;
wire   [25:0] current_sin_V_29_fu_1230_p3;
wire   [14:0] tmp_33_fu_1251_p4;
wire  signed [23:0] sext_ln1496_11_fu_1261_p1;
wire  signed [25:0] sext_ln1332_5_fu_1247_p1;
wire   [23:0] add_ln703_19_fu_1277_p2;
wire   [23:0] sub_ln703_18_fu_1265_p2;
wire   [27:0] add_ln1496_20_fu_1303_p2;
wire   [27:0] select_ln1496_30_fu_1296_p3;
wire   [25:0] current_sin_V_31_fu_1283_p2;
wire   [25:0] current_sin_V_30_fu_1271_p2;
wire  signed [23:0] sext_ln1496_12_fu_1360_p1;
wire  signed [25:0] sext_ln1332_6_fu_1357_p1;
wire   [23:0] add_ln703_21_fu_1373_p2;
wire   [23:0] sub_ln703_20_fu_1363_p2;
wire   [27:0] add_ln1496_22_fu_1397_p2;
wire   [27:0] select_ln1496_33_fu_1390_p3;
wire   [25:0] current_sin_V_34_fu_1378_p2;
wire   [25:0] current_sin_V_33_fu_1368_p2;
wire   [23:0] select_ln1496_32_fu_1383_p3;
wire   [12:0] tmp_41_fu_1425_p4;
wire  signed [23:0] sext_ln1496_13_fu_1435_p1;
wire   [23:0] add_ln703_23_fu_1453_p2;
wire   [23:0] sub_ln703_22_fu_1447_p2;
wire  signed [25:0] sext_ln1332_7_fu_1485_p1;
wire   [27:0] add_ln1496_24_fu_1505_p2;
wire   [27:0] select_ln1496_36_fu_1498_p3;
wire   [25:0] current_sin_V_37_fu_1493_p2;
wire   [25:0] current_sin_V_36_fu_1488_p2;
wire   [25:0] current_sin_V_38_fu_1516_p3;
wire   [11:0] tmp_45_fu_1526_p4;
wire   [27:0] theta_V_13_fu_1510_p2;
wire  signed [23:0] sext_ln1496_14_fu_1536_p1;
wire  signed [25:0] sext_ln1332_8_fu_1523_p1;
wire   [0:0] tmp_46_fu_1540_p3;
wire   [23:0] add_ln703_25_fu_1559_p2;
wire   [23:0] sub_ln703_24_fu_1548_p2;
wire   [23:0] select_ln31_fu_1570_p3;
wire   [25:0] current_sin_V_40_fu_1564_p2;
wire   [25:0] current_sin_V_39_fu_1553_p2;
wire   [25:0] current_sin_V_41_fu_1583_p3;
reg   [13:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
end

cordic_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .theta(theta),
    .sine(sine),
    .sine_ap_vld(sine_ap_vld),
    .cosine(cosine),
    .cosine_ap_vld(cosine_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        current_sin_V_14_reg_1759 <= current_sin_V_14_fu_816_p3;
        select_ln1496_11_reg_1753 <= select_ln1496_11_fu_809_p3;
        theta_V_8_reg_1775 <= theta_V_8_fu_855_p2;
        tmp_14_reg_1765 <= {{select_ln1496_11_fu_809_p3[23:6]}};
        tmp_26_reg_1780 <= theta_V_8_fu_855_p2[32'd27];
        tmp_27_reg_1786 <= theta_V_8_fu_855_p2[32'd27];
        trunc_ln1333_8_reg_1770 <= {{current_sin_V_14_fu_816_p3[25:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        current_sin_V_20_reg_1797 <= current_sin_V_20_fu_976_p3;
        select_ln1496_17_reg_1791 <= select_ln1496_17_fu_969_p3;
        theta_V_9_reg_1813 <= theta_V_9_fu_1015_p2;
        tmp_20_reg_1803 <= {{select_ln1496_17_fu_969_p3[23:8]}};
        tmp_21_reg_1808 <= {{current_sin_V_20_fu_976_p3[25:8]}};
        tmp_30_reg_1818 <= theta_V_9_fu_1015_p2[32'd27];
        tmp_31_reg_1824 <= theta_V_9_fu_1015_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        current_sin_V_26_reg_1835 <= current_sin_V_26_fu_1136_p3;
        select_ln1496_23_reg_1829 <= select_ln1496_23_fu_1129_p3;
        theta_V_10_reg_1851 <= theta_V_10_fu_1175_p2;
        tmp_28_reg_1841 <= {{select_ln1496_23_fu_1129_p3[23:10]}};
        tmp_29_reg_1846 <= {{current_sin_V_26_fu_1136_p3[25:10]}};
        tmp_34_reg_1856 <= theta_V_10_fu_1175_p2[32'd27];
        tmp_35_reg_1862 <= theta_V_10_fu_1175_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        current_sin_V_32_reg_1878 <= current_sin_V_32_fu_1314_p3;
        select_ln1496_29_reg_1867 <= select_ln1496_29_fu_1289_p3;
        theta_V_11_reg_1873 <= theta_V_11_fu_1308_p2;
        tmp_36_reg_1884 <= {{select_ln1496_29_fu_1289_p3[23:12]}};
        tmp_37_reg_1889 <= {{current_sin_V_32_fu_1314_p3[25:12]}};
        tmp_38_reg_1894 <= theta_V_11_fu_1308_p2[32'd27];
        tmp_39_reg_1900 <= theta_V_11_fu_1308_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        current_sin_V_35_reg_1910 <= current_sin_V_35_fu_1408_p3;
        select_ln1496_35_reg_1926 <= select_ln1496_35_fu_1459_p3;
        theta_V_12_reg_1905 <= theta_V_12_fu_1402_p2;
        tmp_40_reg_1916 <= {{select_ln1496_32_fu_1383_p3[23:13]}};
        tmp_42_reg_1921 <= theta_V_12_fu_1402_p2[32'd27];
        tmp_43_reg_1932 <= theta_V_12_fu_1402_p2[32'd27];
        tmp_44_reg_1937 <= {{select_ln1496_35_fu_1459_p3[23:14]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        current_sin_V_8_reg_1721 <= current_sin_V_8_fu_647_p3;
        select_ln1496_5_reg_1716 <= select_ln1496_5_fu_640_p3;
        theta_V_7_reg_1737 <= theta_V_7_fu_686_p2;
        tmp_22_reg_1742 <= theta_V_7_fu_686_p2[32'd27];
        tmp_23_reg_1748 <= theta_V_7_fu_686_p2[32'd27];
        tmp_8_reg_1727 <= {{select_ln1496_5_fu_640_p3[21:4]}};
        trunc_ln1333_4_reg_1732 <= {{current_sin_V_8_fu_647_p3[25:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        theta_V_1_reg_1620 <= theta_V_1_fu_272_p2;
        tmp_3_reg_1625 <= theta_V_1_fu_272_p2[32'd27];
        tmp_4_reg_1631 <= theta_V_1_fu_272_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        theta_V_2_reg_1636 <= theta_V_2_fu_306_p2;
        tmp_6_reg_1641 <= theta_V_2_fu_306_p2[32'd27];
        tmp_7_reg_1647 <= theta_V_2_fu_306_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        theta_V_3_reg_1652 <= theta_V_3_fu_340_p2;
        tmp_10_reg_1663 <= theta_V_3_fu_340_p2[32'd27];
        tmp_9_reg_1657 <= theta_V_3_fu_340_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        theta_V_4_reg_1668 <= theta_V_4_fu_374_p2;
        tmp_12_reg_1673 <= theta_V_4_fu_374_p2[32'd27];
        tmp_13_reg_1679 <= theta_V_4_fu_374_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        theta_V_5_reg_1684 <= theta_V_5_fu_408_p2;
        tmp_15_reg_1689 <= theta_V_5_fu_408_p2[32'd27];
        tmp_16_reg_1695 <= theta_V_5_fu_408_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        theta_V_6_reg_1700 <= theta_V_6_fu_442_p2;
        tmp_18_reg_1705 <= theta_V_6_fu_442_p2[32'd27];
        tmp_19_reg_1711 <= theta_V_6_fu_442_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        theta_V_reg_1604 <= theta_V_fu_238_p2;
        tmp_1_reg_1609 <= theta_V_fu_238_p2[32'd27];
        tmp_2_reg_1615 <= theta_V_fu_238_p2[32'd27];
        tmp_reg_1596 <= theta[32'd27];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        cosine_ap_vld = 1'b1;
    end else begin
        cosine_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sine_ap_vld = 1'b1;
    end else begin
        sine_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1496_10_fu_437_p2 = ($signed(theta_V_5_reg_1684) + $signed(28'd267496798));

assign add_ln1496_12_fu_681_p2 = ($signed(theta_V_6_reg_1700) + $signed(28'd267966099));

assign add_ln1496_14_fu_850_p2 = ($signed(theta_V_7_reg_1737) + $signed(28'd268200773));

assign add_ln1496_16_fu_1010_p2 = ($signed(theta_V_8_reg_1775) + $signed(28'd268318114));

assign add_ln1496_18_fu_1170_p2 = ($signed(theta_V_9_reg_1813) + $signed(28'd268376785));

assign add_ln1496_20_fu_1303_p2 = ($signed(theta_V_10_reg_1851) + $signed(28'd268406121));

assign add_ln1496_22_fu_1397_p2 = ($signed(theta_V_11_reg_1873) + $signed(28'd268420789));

assign add_ln1496_24_fu_1505_p2 = ($signed(theta_V_12_reg_1905) + $signed(28'd268428122));

assign add_ln1496_2_fu_301_p2 = ($signed(theta_V_1_reg_1620) + $signed(28'd253717388));

assign add_ln1496_4_fu_335_p2 = ($signed(theta_V_2_reg_1636) + $signed(28'd260964335));

assign add_ln1496_6_fu_369_p2 = ($signed(theta_V_3_reg_1652) + $signed(28'd264685398));

assign add_ln1496_8_fu_403_p2 = ($signed(theta_V_4_reg_1668) + $signed(28'd266558598));

assign add_ln1496_fu_267_p2 = ($signed(theta_V_reg_1604) + $signed(28'd240579981));

assign add_ln703_11_fu_957_p2 = ($signed(select_ln1496_14_fu_903_p3) + $signed(sext_ln1496_7_fu_941_p1));

assign add_ln703_13_fu_1053_p2 = ($signed(select_ln1496_17_reg_1791) + $signed(sext_ln1496_8_fu_1040_p1));

assign add_ln703_15_fu_1117_p2 = ($signed(select_ln1496_20_fu_1063_p3) + $signed(sext_ln1496_9_fu_1101_p1));

assign add_ln703_17_fu_1213_p2 = ($signed(select_ln1496_23_reg_1829) + $signed(sext_ln1496_10_fu_1200_p1));

assign add_ln703_19_fu_1277_p2 = ($signed(select_ln1496_26_fu_1223_p3) + $signed(sext_ln1496_11_fu_1261_p1));

assign add_ln703_21_fu_1373_p2 = ($signed(select_ln1496_29_reg_1867) + $signed(sext_ln1496_12_fu_1360_p1));

assign add_ln703_23_fu_1453_p2 = ($signed(select_ln1496_32_fu_1383_p3) + $signed(sext_ln1496_13_fu_1435_p1));

assign add_ln703_25_fu_1559_p2 = ($signed(select_ln1496_35_reg_1926) + $signed(sext_ln1496_14_fu_1536_p1));

assign add_ln703_3_fu_628_p2 = ($signed(zext_ln1496_1_fu_573_p1) + $signed(sext_ln1496_1_fu_612_p1));

assign add_ln703_5_fu_728_p2 = ($signed(sext_ln1496_2_fu_708_p1) + $signed(sext_ln1496_3_fu_714_p1));

assign add_ln703_7_fu_797_p2 = ($signed(sext_ln1496_4_fu_746_p1) + $signed(sext_ln1496_5_fu_781_p1));

assign add_ln703_9_fu_893_p2 = ($signed(select_ln1496_11_reg_1753) + $signed(sext_ln1496_6_fu_880_p1));

assign add_ln703_fu_554_p2 = ($signed(zext_ln1496_fu_499_p1) + $signed(sext_ln1496_fu_538_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cosine = $signed(select_ln31_fu_1570_p3);

assign current_sin_V_10_fu_734_p2 = ($signed(current_sin_V_8_reg_1721) - $signed(sext_ln1332_fu_711_p1));

assign current_sin_V_11_fu_750_p3 = ((tmp_9_reg_1657[0:0] == 1'b1) ? current_sin_V_10_fu_734_p2 : current_sin_V_9_fu_723_p2);

assign current_sin_V_12_fu_791_p2 = ($signed(current_sin_V_11_fu_750_p3) + $signed(sext_ln1332_1_fu_767_p1));

assign current_sin_V_13_fu_803_p2 = ($signed(current_sin_V_11_fu_750_p3) - $signed(sext_ln1332_1_fu_767_p1));

assign current_sin_V_14_fu_816_p3 = ((tmp_12_reg_1673[0:0] == 1'b1) ? current_sin_V_13_fu_803_p2 : current_sin_V_12_fu_791_p2);

assign current_sin_V_15_fu_888_p2 = ($signed(current_sin_V_14_reg_1759) + $signed(sext_ln1332_2_fu_877_p1));

assign current_sin_V_16_fu_898_p2 = ($signed(current_sin_V_14_reg_1759) - $signed(sext_ln1332_2_fu_877_p1));

assign current_sin_V_17_fu_910_p3 = ((tmp_15_reg_1689[0:0] == 1'b1) ? current_sin_V_16_fu_898_p2 : current_sin_V_15_fu_888_p2);

assign current_sin_V_18_fu_951_p2 = ($signed(current_sin_V_17_fu_910_p3) + $signed(sext_ln1333_fu_927_p1));

assign current_sin_V_19_fu_963_p2 = ($signed(current_sin_V_17_fu_910_p3) - $signed(sext_ln1333_fu_927_p1));

assign current_sin_V_1_fu_485_p3 = ((tmp_reg_1596[0:0] == 1'b1) ? 21'd1142026 : 21'd318376);

assign current_sin_V_20_fu_976_p3 = ((tmp_18_reg_1705[0:0] == 1'b1) ? current_sin_V_19_fu_963_p2 : current_sin_V_18_fu_951_p2);

assign current_sin_V_21_fu_1048_p2 = ($signed(current_sin_V_20_reg_1797) + $signed(sext_ln1333_1_fu_1037_p1));

assign current_sin_V_22_fu_1058_p2 = ($signed(current_sin_V_20_reg_1797) - $signed(sext_ln1333_1_fu_1037_p1));

assign current_sin_V_23_fu_1070_p3 = ((tmp_22_reg_1742[0:0] == 1'b1) ? current_sin_V_22_fu_1058_p2 : current_sin_V_21_fu_1048_p2);

assign current_sin_V_24_fu_1111_p2 = ($signed(current_sin_V_23_fu_1070_p3) + $signed(sext_ln1332_3_fu_1087_p1));

assign current_sin_V_25_fu_1123_p2 = ($signed(current_sin_V_23_fu_1070_p3) - $signed(sext_ln1332_3_fu_1087_p1));

assign current_sin_V_26_fu_1136_p3 = ((tmp_26_reg_1780[0:0] == 1'b1) ? current_sin_V_25_fu_1123_p2 : current_sin_V_24_fu_1111_p2);

assign current_sin_V_27_fu_1208_p2 = ($signed(current_sin_V_26_reg_1835) + $signed(sext_ln1332_4_fu_1197_p1));

assign current_sin_V_28_fu_1218_p2 = ($signed(current_sin_V_26_reg_1835) - $signed(sext_ln1332_4_fu_1197_p1));

assign current_sin_V_29_fu_1230_p3 = ((tmp_30_reg_1818[0:0] == 1'b1) ? current_sin_V_28_fu_1218_p2 : current_sin_V_27_fu_1208_p2);

assign current_sin_V_2_fu_503_p3 = ((tmp_1_reg_1609[0:0] == 1'b1) ? current_sin_V_1_fu_485_p3 : current_sin_V_fu_471_p3);

assign current_sin_V_30_fu_1271_p2 = ($signed(current_sin_V_29_fu_1230_p3) + $signed(sext_ln1332_5_fu_1247_p1));

assign current_sin_V_31_fu_1283_p2 = ($signed(current_sin_V_29_fu_1230_p3) - $signed(sext_ln1332_5_fu_1247_p1));

assign current_sin_V_32_fu_1314_p3 = ((tmp_34_reg_1856[0:0] == 1'b1) ? current_sin_V_31_fu_1283_p2 : current_sin_V_30_fu_1271_p2);

assign current_sin_V_33_fu_1368_p2 = ($signed(current_sin_V_32_reg_1878) + $signed(sext_ln1332_6_fu_1357_p1));

assign current_sin_V_34_fu_1378_p2 = ($signed(current_sin_V_32_reg_1878) - $signed(sext_ln1332_6_fu_1357_p1));

assign current_sin_V_35_fu_1408_p3 = ((tmp_38_reg_1894[0:0] == 1'b1) ? current_sin_V_34_fu_1378_p2 : current_sin_V_33_fu_1368_p2);

assign current_sin_V_36_fu_1488_p2 = ($signed(current_sin_V_35_reg_1910) + $signed(sext_ln1332_7_fu_1485_p1));

assign current_sin_V_37_fu_1493_p2 = ($signed(current_sin_V_35_reg_1910) - $signed(sext_ln1332_7_fu_1485_p1));

assign current_sin_V_38_fu_1516_p3 = ((tmp_42_reg_1921[0:0] == 1'b1) ? current_sin_V_37_fu_1493_p2 : current_sin_V_36_fu_1488_p2);

assign current_sin_V_39_fu_1553_p2 = ($signed(current_sin_V_38_fu_1516_p3) + $signed(sext_ln1332_8_fu_1523_p1));

assign current_sin_V_3_fu_548_p2 = ($signed(sext_ln20_fu_510_p1) + $signed(zext_ln1332_fu_524_p1));

assign current_sin_V_40_fu_1564_p2 = ($signed(current_sin_V_38_fu_1516_p3) - $signed(sext_ln1332_8_fu_1523_p1));

assign current_sin_V_41_fu_1583_p3 = ((tmp_46_fu_1540_p3[0:0] == 1'b1) ? current_sin_V_40_fu_1564_p2 : current_sin_V_39_fu_1553_p2);

assign current_sin_V_4_fu_560_p2 = ($signed(sext_ln20_fu_510_p1) - $signed(zext_ln1332_fu_524_p1));

assign current_sin_V_5_fu_577_p3 = ((tmp_3_reg_1625[0:0] == 1'b1) ? current_sin_V_4_fu_560_p2 : current_sin_V_3_fu_548_p2);

assign current_sin_V_6_fu_622_p2 = ($signed(sext_ln20_1_fu_584_p1) + $signed(zext_ln1332_1_fu_598_p1));

assign current_sin_V_7_fu_634_p2 = ($signed(sext_ln20_1_fu_584_p1) - $signed(zext_ln1332_1_fu_598_p1));

assign current_sin_V_8_fu_647_p3 = ((tmp_6_reg_1641[0:0] == 1'b1) ? current_sin_V_7_fu_634_p2 : current_sin_V_6_fu_622_p2);

assign current_sin_V_9_fu_723_p2 = ($signed(current_sin_V_8_reg_1721) + $signed(sext_ln1332_fu_711_p1));

assign current_sin_V_fu_471_p3 = ((tmp_reg_1596[0:0] == 1'b1) ? 21'd1778776 : 21'd955126);

assign r_V_fu_514_p4 = {{select_ln1333_fu_492_p3[19:2]}};

assign select_ln1333_fu_492_p3 = ((tmp_1_reg_1609[0:0] == 1'b1) ? select_ln703_1_fu_478_p3 : select_ln703_fu_464_p3);

assign select_ln1496_11_fu_809_p3 = ((tmp_12_reg_1673[0:0] == 1'b1) ? add_ln703_7_fu_797_p2 : sub_ln703_6_fu_785_p2);

assign select_ln1496_12_fu_396_p3 = ((tmp_13_reg_1679[0:0] == 1'b1) ? 28'd3753716 : 28'd0);

assign select_ln1496_14_fu_903_p3 = ((tmp_15_reg_1689[0:0] == 1'b1) ? add_ln703_9_fu_893_p2 : sub_ln703_8_fu_883_p2);

assign select_ln1496_15_fu_430_p3 = ((tmp_16_reg_1695[0:0] == 1'b1) ? 28'd1877316 : 28'd0);

assign select_ln1496_17_fu_969_p3 = ((tmp_18_reg_1705[0:0] == 1'b1) ? add_ln703_11_fu_957_p2 : sub_ln703_10_fu_945_p2);

assign select_ln1496_18_fu_674_p3 = ((tmp_19_reg_1711[0:0] == 1'b1) ? 28'd938714 : 28'd0);

assign select_ln1496_20_fu_1063_p3 = ((tmp_22_reg_1742[0:0] == 1'b1) ? add_ln703_13_fu_1053_p2 : sub_ln703_12_fu_1043_p2);

assign select_ln1496_21_fu_843_p3 = ((tmp_23_reg_1748[0:0] == 1'b1) ? 28'd469366 : 28'd0);

assign select_ln1496_23_fu_1129_p3 = ((tmp_26_reg_1780[0:0] == 1'b1) ? add_ln703_15_fu_1117_p2 : sub_ln703_14_fu_1105_p2);

assign select_ln1496_24_fu_1003_p3 = ((tmp_27_reg_1786[0:0] == 1'b1) ? 28'd234684 : 28'd0);

assign select_ln1496_26_fu_1223_p3 = ((tmp_30_reg_1818[0:0] == 1'b1) ? add_ln703_17_fu_1213_p2 : sub_ln703_16_fu_1203_p2);

assign select_ln1496_27_fu_1163_p3 = ((tmp_31_reg_1824[0:0] == 1'b1) ? 28'd117342 : 28'd0);

assign select_ln1496_29_fu_1289_p3 = ((tmp_34_reg_1856[0:0] == 1'b1) ? add_ln703_19_fu_1277_p2 : sub_ln703_18_fu_1265_p2);

assign select_ln1496_2_fu_566_p3 = ((tmp_3_reg_1625[0:0] == 1'b1) ? add_ln703_fu_554_p2 : sub_ln703_fu_542_p2);

assign select_ln1496_30_fu_1296_p3 = ((tmp_35_reg_1862[0:0] == 1'b1) ? 28'd58670 : 28'd0);

assign select_ln1496_32_fu_1383_p3 = ((tmp_38_reg_1894[0:0] == 1'b1) ? add_ln703_21_fu_1373_p2 : sub_ln703_20_fu_1363_p2);

assign select_ln1496_33_fu_1390_p3 = ((tmp_39_reg_1900[0:0] == 1'b1) ? 28'd29334 : 28'd0);

assign select_ln1496_35_fu_1459_p3 = ((tmp_42_fu_1439_p3[0:0] == 1'b1) ? add_ln703_23_fu_1453_p2 : sub_ln703_22_fu_1447_p2);

assign select_ln1496_36_fu_1498_p3 = ((tmp_43_reg_1932[0:0] == 1'b1) ? 28'd14668 : 28'd0);

assign select_ln1496_3_fu_294_p3 = ((tmp_4_reg_1631[0:0] == 1'b1) ? 28'd29436136 : 28'd0);

assign select_ln1496_5_fu_640_p3 = ((tmp_6_reg_1641[0:0] == 1'b1) ? add_ln703_3_fu_628_p2 : sub_ln703_2_fu_616_p2);

assign select_ln1496_6_fu_328_p3 = ((tmp_7_reg_1647[0:0] == 1'b1) ? 28'd14942242 : 28'd0);

assign select_ln1496_8_fu_739_p3 = ((tmp_9_reg_1657[0:0] == 1'b1) ? add_ln703_5_fu_728_p2 : sub_ln703_4_fu_717_p2);

assign select_ln1496_9_fu_362_p3 = ((tmp_10_reg_1663[0:0] == 1'b1) ? 28'd7500116 : 28'd0);

assign select_ln1496_fu_260_p3 = ((tmp_2_reg_1615[0:0] == 1'b1) ? 28'd55710950 : 28'd0);

assign select_ln31_1_fu_230_p3 = ((tmp_fu_222_p3[0:0] == 1'b1) ? 28'd47185920 : 28'd221249536);

assign select_ln31_fu_1570_p3 = ((tmp_46_fu_1540_p3[0:0] == 1'b1) ? add_ln703_25_fu_1559_p2 : sub_ln703_24_fu_1548_p2);

assign select_ln703_1_fu_478_p3 = ((tmp_reg_1596[0:0] == 1'b1) ? 20'd318375 : 20'd955126);

assign select_ln703_fu_464_p3 = ((tmp_reg_1596[0:0] == 1'b1) ? 20'd955127 : 20'd318376);

assign sext_ln1332_1_fu_767_p1 = $signed(tmp_11_fu_757_p4);

assign sext_ln1332_2_fu_877_p1 = $signed(tmp_14_reg_1765);

assign sext_ln1332_3_fu_1087_p1 = $signed(tmp_24_fu_1077_p4);

assign sext_ln1332_4_fu_1197_p1 = $signed(tmp_28_reg_1841);

assign sext_ln1332_5_fu_1247_p1 = $signed(tmp_32_fu_1237_p4);

assign sext_ln1332_6_fu_1357_p1 = $signed(tmp_36_reg_1884);

assign sext_ln1332_7_fu_1485_p1 = $signed(tmp_40_reg_1916);

assign sext_ln1332_8_fu_1523_p1 = $signed(tmp_44_reg_1937);

assign sext_ln1332_fu_711_p1 = $signed(tmp_8_reg_1727);

assign sext_ln1333_1_fu_1037_p1 = $signed(tmp_20_reg_1803);

assign sext_ln1333_fu_927_p1 = $signed(tmp_17_fu_917_p4);

assign sext_ln1496_10_fu_1200_p1 = $signed(tmp_29_reg_1846);

assign sext_ln1496_11_fu_1261_p1 = $signed(tmp_33_fu_1251_p4);

assign sext_ln1496_12_fu_1360_p1 = $signed(tmp_37_reg_1889);

assign sext_ln1496_13_fu_1435_p1 = $signed(tmp_41_fu_1425_p4);

assign sext_ln1496_14_fu_1536_p1 = $signed(tmp_45_fu_1526_p4);

assign sext_ln1496_1_fu_612_p1 = $signed(trunc_ln1333_2_fu_602_p4);

assign sext_ln1496_2_fu_708_p1 = select_ln1496_5_reg_1716;

assign sext_ln1496_3_fu_714_p1 = $signed(trunc_ln1333_4_reg_1732);

assign sext_ln1496_4_fu_746_p1 = select_ln1496_8_fu_739_p3;

assign sext_ln1496_5_fu_781_p1 = $signed(trunc_ln1333_6_fu_771_p4);

assign sext_ln1496_6_fu_880_p1 = $signed(trunc_ln1333_8_reg_1770);

assign sext_ln1496_7_fu_941_p1 = $signed(trunc_ln1333_s_fu_931_p4);

assign sext_ln1496_8_fu_1040_p1 = $signed(tmp_21_reg_1808);

assign sext_ln1496_9_fu_1101_p1 = $signed(tmp_25_fu_1091_p4);

assign sext_ln1496_fu_538_p1 = $signed(trunc_ln2_fu_528_p4);

assign sext_ln20_1_fu_584_p1 = current_sin_V_5_fu_577_p3;

assign sext_ln20_fu_510_p1 = current_sin_V_2_fu_503_p3;

assign sine = $signed(current_sin_V_41_fu_1583_p3);

assign sub_ln703_10_fu_945_p2 = ($signed(select_ln1496_14_fu_903_p3) - $signed(sext_ln1496_7_fu_941_p1));

assign sub_ln703_12_fu_1043_p2 = ($signed(select_ln1496_17_reg_1791) - $signed(sext_ln1496_8_fu_1040_p1));

assign sub_ln703_14_fu_1105_p2 = ($signed(select_ln1496_20_fu_1063_p3) - $signed(sext_ln1496_9_fu_1101_p1));

assign sub_ln703_16_fu_1203_p2 = ($signed(select_ln1496_23_reg_1829) - $signed(sext_ln1496_10_fu_1200_p1));

assign sub_ln703_18_fu_1265_p2 = ($signed(select_ln1496_26_fu_1223_p3) - $signed(sext_ln1496_11_fu_1261_p1));

assign sub_ln703_20_fu_1363_p2 = ($signed(select_ln1496_29_reg_1867) - $signed(sext_ln1496_12_fu_1360_p1));

assign sub_ln703_22_fu_1447_p2 = ($signed(select_ln1496_32_fu_1383_p3) - $signed(sext_ln1496_13_fu_1435_p1));

assign sub_ln703_24_fu_1548_p2 = ($signed(select_ln1496_35_reg_1926) - $signed(sext_ln1496_14_fu_1536_p1));

assign sub_ln703_2_fu_616_p2 = ($signed(zext_ln1496_1_fu_573_p1) - $signed(sext_ln1496_1_fu_612_p1));

assign sub_ln703_4_fu_717_p2 = ($signed(sext_ln1496_2_fu_708_p1) - $signed(sext_ln1496_3_fu_714_p1));

assign sub_ln703_6_fu_785_p2 = ($signed(sext_ln1496_4_fu_746_p1) - $signed(sext_ln1496_5_fu_781_p1));

assign sub_ln703_8_fu_883_p2 = ($signed(select_ln1496_11_reg_1753) - $signed(sext_ln1496_6_fu_880_p1));

assign sub_ln703_fu_542_p2 = ($signed(zext_ln1496_fu_499_p1) - $signed(sext_ln1496_fu_538_p1));

assign theta_V_10_fu_1175_p2 = (add_ln1496_18_fu_1170_p2 + select_ln1496_27_fu_1163_p3);

assign theta_V_11_fu_1308_p2 = (add_ln1496_20_fu_1303_p2 + select_ln1496_30_fu_1296_p3);

assign theta_V_12_fu_1402_p2 = (add_ln1496_22_fu_1397_p2 + select_ln1496_33_fu_1390_p3);

assign theta_V_13_fu_1510_p2 = (add_ln1496_24_fu_1505_p2 + select_ln1496_36_fu_1498_p3);

assign theta_V_1_fu_272_p2 = (add_ln1496_fu_267_p2 + select_ln1496_fu_260_p3);

assign theta_V_2_fu_306_p2 = (add_ln1496_2_fu_301_p2 + select_ln1496_3_fu_294_p3);

assign theta_V_3_fu_340_p2 = (add_ln1496_4_fu_335_p2 + select_ln1496_6_fu_328_p3);

assign theta_V_4_fu_374_p2 = (add_ln1496_6_fu_369_p2 + select_ln1496_9_fu_362_p3);

assign theta_V_5_fu_408_p2 = (add_ln1496_8_fu_403_p2 + select_ln1496_12_fu_396_p3);

assign theta_V_6_fu_442_p2 = (add_ln1496_10_fu_437_p2 + select_ln1496_15_fu_430_p3);

assign theta_V_7_fu_686_p2 = (add_ln1496_12_fu_681_p2 + select_ln1496_18_fu_674_p3);

assign theta_V_8_fu_855_p2 = (add_ln1496_14_fu_850_p2 + select_ln1496_21_fu_843_p3);

assign theta_V_9_fu_1015_p2 = (add_ln1496_16_fu_1010_p2 + select_ln1496_24_fu_1003_p3);

assign theta_V_fu_238_p2 = (select_ln31_1_fu_230_p3 + theta);

assign tmp_11_fu_757_p4 = {{select_ln1496_8_fu_739_p3[22:5]}};

assign tmp_17_fu_917_p4 = {{select_ln1496_14_fu_903_p3[23:7]}};

assign tmp_24_fu_1077_p4 = {{select_ln1496_20_fu_1063_p3[23:9]}};

assign tmp_25_fu_1091_p4 = {{current_sin_V_23_fu_1070_p3[25:9]}};

assign tmp_32_fu_1237_p4 = {{select_ln1496_26_fu_1223_p3[23:11]}};

assign tmp_33_fu_1251_p4 = {{current_sin_V_29_fu_1230_p3[25:11]}};

assign tmp_41_fu_1425_p4 = {{current_sin_V_35_fu_1408_p3[25:13]}};

assign tmp_42_fu_1439_p3 = theta_V_12_fu_1402_p2[32'd27];

assign tmp_45_fu_1526_p4 = {{current_sin_V_38_fu_1516_p3[25:14]}};

assign tmp_46_fu_1540_p3 = theta_V_13_fu_1510_p2[32'd27];

assign tmp_5_fu_588_p4 = {{select_ln1496_2_fu_566_p3[20:3]}};

assign tmp_fu_222_p3 = theta[32'd27];

assign trunc_ln1333_2_fu_602_p4 = {{current_sin_V_5_fu_577_p3[21:3]}};

assign trunc_ln1333_6_fu_771_p4 = {{current_sin_V_11_fu_750_p3[25:5]}};

assign trunc_ln1333_s_fu_931_p4 = {{current_sin_V_17_fu_910_p3[25:7]}};

assign trunc_ln2_fu_528_p4 = {{current_sin_V_2_fu_503_p3[20:2]}};

assign zext_ln1332_1_fu_598_p1 = tmp_5_fu_588_p4;

assign zext_ln1332_fu_524_p1 = r_V_fu_514_p4;

assign zext_ln1496_1_fu_573_p1 = select_ln1496_2_fu_566_p3;

assign zext_ln1496_fu_499_p1 = select_ln1333_fu_492_p3;

endmodule //cordic
